// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Chirp struct {
	ID        uuid.UUID
	Body      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	HashedPassword string
}
