services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: chirpy_user
      POSTGRES_PASSWORD: chirpy_pass
      POSTGRES_DB: chirpy_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chirpy_network

volumes:
  postgres_data:

networks:
  chirpy_network:
    driver: bridge
